### ISSUE TITLE
Graddle Support?

### ISSUE THREAD

**Issue by n8stowell82** [askcs/android-simple-camera#1]
Hello, I am a relative beginner with Android and new to the Graddle/Maven repositories and the difference between them.  I have created a new project that requires a camera to take pictures.  I cannot for the life of me get the default android camera tutorial to work, so I went out in search of projects that might make this easier.  I found yours, but see that it requires maven to install it and build.  Please forgive my ignorance, but is there a way to add this as a dependency in graddle and build it that way? or do I need to have maven to get this into my project?  Thank you so much!

**Comment by leonjoosse** [comment]
Hi, I updated the README. You do need Maven to be installed in order to use this library as a dependency when following the README. Otherwise, you can clone the project to your local machine and use another way of having it as a dependency, for that, you might take a look at this: http://stackoverflow.com/questions/16763090/how-to-export-library-to-jar-in-android-studio .

**Comment by n8stowell82** [comment]
Thank you for the update!
