### ISSUE TITLE
getHost() is not resolve in android-23.

### ISSUE THREAD

**Issue by thitoo** [askcs/android-simple-camera#3]
public CameraHost **getHost()** {
        if (host == null) {
            host = new SimpleCameraHost(getActivity());
        }

```
    return host;
}
```

**Comment by localh0rzd** [comment]
Since API 23, you have to request certain permissions from the user. The camera permission is one of these. The developer using the library should take care of this step inside the actual project. Since you show a toast on failed access rather crashing the application, I don't really see an issue here. I have added this to the README though.

See: https://developer.android.com/training/permissions/requesting.html
